package com.bomwebportal.lts.dao.bom;

import com.bomwebportal.dao.BaseDAO;
import com.bomwebportal.exception.DAOException;

public class BomInvPreassgnDAO extends BaseDAO {
	
	private static final String SQL_ADD_DUMMY_INV_PREASSGN = 
		"INSERT INTO B_INV_PREASSGN (OC_ID,DTL_ID,DTL_SEQ,BUILD_ID,EN_EXCHNG_ID,VISIT_IND,ASSG_REA_CD,NEW_SRV_NUM,LNAS_ASSGMT_RETURN_CD,SHRD_DP_IND, " +
		"WIRED_OFF_LMT_IND,REF_BUILD_ID,REF_EXCHNG_ID,SRV_NN,BANR_CRNR_REQ,BLK_WIRE_PAIR_NUM,DSIDE_PAIR_NUM,ESIDE_PAIR_NUM,SKT_IND,DPSDF_CD,DPSDF_PAIR_NUM, " +
		"CABINET_SEQ_NUM,MDF_SEQ_NUM,PIN_NUM,MDFBAR_SEQ_NUM,CABLE_CD,CABLE_PAIR_NUM,SHR_PAIR_NUM,BC_ORDER_ID,REMOTE_MDF_SEQ_NUM,TERMNTR_ID,TERMNTR_TYPE_CD, " +
		"TERM_PAIR_NUM,HOR_TYPE_CD,VERT_TYPE_CD,CABLE_STS_CD,TIE_PAIR_NUM,JUNCTION_MESSAGE,RE_USE_IND,SRV_EN,NN_EXCHNG_ID,EN_ASSGN_DATE,EN_MOD_COUNT, " +
		"LAST_UPD_DATE,LAST_UPD_BY,LAST_SUBMIT_DATE,INTERLINK_IND,PAYPHONE_ID,PAYPHONE_ASSGN_STS,PROV_IND,PROV_DATE,DN_ASSGN_STS,DN_ASSGN_DATE,LAST_ASSGN_SRV_NUM, " +
		"GATEWAY_NUM,INVENT_STS_CD,ACTN_IND7BNR,ACTN_IND7NRS,BBG_ID,MBG_ID,LINE_EQMT_NUM) VALUES " +
		"(?,?,?,NULL,NULL,NULL,NULL,?,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL, " +
		"NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,?,NULL,NULL,NULL, " +
		"NULL,NULL,SYSDATE,?,NULL,NULL,NULL,NULL, " +
		"NULL,NULL,?,NULL,NULL,?,?,NULL,NULL,NULL,NULL,NULL) ";

	public void insertDummyInvPreassgn(String ocId, String dtlId, String sbId, String srvNum, 
			String stsCd, String userId) throws DAOException {
		try {
			simpleJdbcTemplate.update(SQL_ADD_DUMMY_INV_PREASSGN, ocId, dtlId, "1", srvNum, sbId, 
					userId, "P", "0", stsCd);
		} catch (Exception e) {
			logger.error("Exception caught in insertDummyInvPreassgn()", e);
			throw new DAOException(e.getMessage(), e);
		}	
	}
	
}
