
package com.pccw.custProfileGateway.custProfile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CustProfileSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustProfileSoap {


    /**
     * 
     * @param psDocNum
     * @param psDN
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.BillRegWrapperDTO
     */
    @WebMethod(action = "http://www.openuri.org/getBillRegistration")
    @WebResult(name = "getBillRegistrationResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getBillRegistration", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetBillRegistration")
    @ResponseWrapper(localName = "getBillRegistrationResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetBillRegistrationResponse")
    public BillRegWrapperDTO getBillRegistration(
        @WebParam(name = "psDN", targetNamespace = "http://www.openuri.org/")
        String psDN,
        @WebParam(name = "psDocNum", targetNamespace = "http://www.openuri.org/")
        String psDocNum);

    /**
     * 
     * @param psLob
     * @param psCustNum
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.AcctEnqWrapperDTO
     */
    @WebMethod(action = "http://www.openuri.org/getAccountEnquiry")
    @WebResult(name = "getAccountEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAccountEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetAccountEnquiry")
    @ResponseWrapper(localName = "getAccountEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetAccountEnquiryResponse")
    public AcctEnqWrapperDTO getAccountEnquiry(
        @WebParam(name = "psCustNum", targetNamespace = "http://www.openuri.org/")
        String psCustNum,
        @WebParam(name = "psLob", targetNamespace = "http://www.openuri.org/")
        String psLob);

    /**
     * 
     * @param psCustNum
     * @param psServiceNum
     * @param psServiceType
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.TermPlanEnqWrapperDTO
     */
    @WebMethod(action = "http://www.openuri.org/getTermPlanEnquiry")
    @WebResult(name = "getTermPlanEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getTermPlanEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetTermPlanEnquiry")
    @ResponseWrapper(localName = "getTermPlanEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetTermPlanEnquiryResponse")
    public TermPlanEnqWrapperDTO getTermPlanEnquiry(
        @WebParam(name = "psServiceType", targetNamespace = "http://www.openuri.org/")
        String psServiceType,
        @WebParam(name = "psServiceNum", targetNamespace = "http://www.openuri.org/")
        String psServiceNum,
        @WebParam(name = "psCustNum", targetNamespace = "http://www.openuri.org/")
        String psCustNum);

    /**
     * 
     * @param psSrvType
     * @param psCustNum
     * @param psSrvNum
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.CallPlanEnqWrapperDTO
     */
    @WebMethod(action = "http://www.openuri.org/getCallPlanEnquiry")
    @WebResult(name = "getCallPlanEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCallPlanEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCallPlanEnquiry")
    @ResponseWrapper(localName = "getCallPlanEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCallPlanEnquiryResponse")
    public CallPlanEnqWrapperDTO getCallPlanEnquiry(
        @WebParam(name = "psCustNum", targetNamespace = "http://www.openuri.org/")
        String psCustNum,
        @WebParam(name = "psSrvType", targetNamespace = "http://www.openuri.org/")
        String psSrvType,
        @WebParam(name = "psSrvNum", targetNamespace = "http://www.openuri.org/")
        String psSrvNum);

    /**
     * 
     * @param psSrvSeq
     * @param psPlanHolderKey
     * @param psPlanCd
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.CallPlanDtlEnqWrapperDTO
     */
    @WebMethod(action = "http://www.openuri.org/getCallPlanDtlEnquiry")
    @WebResult(name = "getCallPlanDtlEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCallPlanDtlEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCallPlanDtlEnquiry")
    @ResponseWrapper(localName = "getCallPlanDtlEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCallPlanDtlEnquiryResponse")
    public CallPlanDtlEnqWrapperDTO getCallPlanDtlEnquiry(
        @WebParam(name = "psPlanCd", targetNamespace = "http://www.openuri.org/")
        String psPlanCd,
        @WebParam(name = "psPlanHolderKey", targetNamespace = "http://www.openuri.org/")
        String psPlanHolderKey,
        @WebParam(name = "psSrvSeq", targetNamespace = "http://www.openuri.org/")
        String psSrvSeq);

    /**
     * 
     * @param custNum
     * @param systemID
     * @param custLevel
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.ContactInfoEnqResponse
     */
    @WebMethod(action = "http://www.openuri.org/getPrimaryContactInfo")
    @WebResult(name = "getPrimaryContactInfoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getPrimaryContactInfo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetPrimaryContactInfo")
    @ResponseWrapper(localName = "getPrimaryContactInfoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetPrimaryContactInfoResponse")
    public ContactInfoEnqResponse getPrimaryContactInfo(
        @WebParam(name = "custNum", targetNamespace = "http://www.openuri.org/")
        String custNum,
        @WebParam(name = "systemID", targetNamespace = "http://www.openuri.org/")
        String systemID,
        @WebParam(name = "custLevel", targetNamespace = "http://www.openuri.org/")
        int custLevel);

    /**
     * 
     * @param custNum
     * @param contactInfoDTO
     * @param systemID
     * @param custLevel
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.ContactInfoUpdResponse
     */
    @WebMethod(action = "http://www.openuri.org/updateContactInfo")
    @WebResult(name = "updateContactInfoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "updateContactInfo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.UpdateContactInfo")
    @ResponseWrapper(localName = "updateContactInfoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.UpdateContactInfoResponse")
    public ContactInfoUpdResponse updateContactInfo(
        @WebParam(name = "custNum", targetNamespace = "http://www.openuri.org/")
        String custNum,
        @WebParam(name = "systemID", targetNamespace = "http://www.openuri.org/")
        String systemID,
        @WebParam(name = "custLevel", targetNamespace = "http://www.openuri.org/")
        int custLevel,
        @WebParam(name = "contactInfoDTO", targetNamespace = "http://www.openuri.org/")
        ContactInfoDTO contactInfoDTO);

    /**
     * 
     * @param custNum
     * @param contactInfoDTO
     * @param systemID
     * @param custLevel
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.ContactInfoUpdResponse
     */
    @WebMethod(operationName = "AddContactInfo", action = "http://www.openuri.org/AddContactInfo")
    @WebResult(name = "AddContactInfoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "AddContactInfo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.AddContactInfo")
    @ResponseWrapper(localName = "AddContactInfoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.AddContactInfoResponse")
    public ContactInfoUpdResponse addContactInfo(
        @WebParam(name = "custNum", targetNamespace = "http://www.openuri.org/")
        String custNum,
        @WebParam(name = "systemID", targetNamespace = "http://www.openuri.org/")
        String systemID,
        @WebParam(name = "custLevel", targetNamespace = "http://www.openuri.org/")
        int custLevel,
        @WebParam(name = "contactInfoDTO", targetNamespace = "http://www.openuri.org/")
        ContactInfoDTO contactInfoDTO);

    /**
     * 
     * @param srvType
     * @param acctNum
     * @param systemId
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.ValidateCustInfoEnqResponse
     */
    @WebMethod(action = "http://www.openuri.org/validateCustInfo")
    @WebResult(name = "validateCustInfoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "validateCustInfo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.ValidateCustInfo")
    @ResponseWrapper(localName = "validateCustInfoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.ValidateCustInfoResponse")
    public ValidateCustInfoEnqResponse validateCustInfo(
        @WebParam(name = "systemId", targetNamespace = "http://www.openuri.org/")
        String systemId,
        @WebParam(name = "acctNum", targetNamespace = "http://www.openuri.org/")
        String acctNum,
        @WebParam(name = "srvType", targetNamespace = "http://www.openuri.org/")
        String srvType,
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum);

    /**
     * 
     * @param psDocNum
     * @param psSrvType
     * @param psDocType
     * @param psDN
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.CustNumEnqResponse
     */
    @WebMethod(action = "http://www.openuri.org/getCustNumEnquiry")
    @WebResult(name = "getCustNumEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCustNumEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCustNumEnquiry")
    @ResponseWrapper(localName = "getCustNumEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCustNumEnquiryResponse")
    public CustNumEnqResponse getCustNumEnquiry(
        @WebParam(name = "psDN", targetNamespace = "http://www.openuri.org/")
        String psDN,
        @WebParam(name = "psDocNum", targetNamespace = "http://www.openuri.org/")
        String psDocNum,
        @WebParam(name = "psSrvType", targetNamespace = "http://www.openuri.org/")
        String psSrvType,
        @WebParam(name = "psDocType", targetNamespace = "http://www.openuri.org/")
        String psDocType);

    /**
     * 
     * @param psSrvType
     * @param psCustNum
     * @param psSrvNum
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.CallPlanEnqWrapperDTO
     */
    @WebMethod(action = "http://www.openuri.org/getCrCallPlanEnquiry")
    @WebResult(name = "getCrCallPlanEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCrCallPlanEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCrCallPlanEnquiry")
    @ResponseWrapper(localName = "getCrCallPlanEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCrCallPlanEnquiryResponse")
    public CallPlanEnqWrapperDTO getCrCallPlanEnquiry(
        @WebParam(name = "psCustNum", targetNamespace = "http://www.openuri.org/")
        String psCustNum,
        @WebParam(name = "psSrvType", targetNamespace = "http://www.openuri.org/")
        String psSrvType,
        @WebParam(name = "psSrvNum", targetNamespace = "http://www.openuri.org/")
        String psSrvNum);

    /**
     * 
     * @param custTagEnqBaseDTO
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.CustTagEnqResponse
     */
    @WebMethod(action = "http://www.openuri.org/getPremierCustEnquiry")
    @WebResult(name = "getPremierCustEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getPremierCustEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetPremierCustEnquiry")
    @ResponseWrapper(localName = "getPremierCustEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetPremierCustEnquiryResponse")
    public CustTagEnqResponse getPremierCustEnquiry(
        @WebParam(name = "custTagEnqBaseDTO", targetNamespace = "http://www.openuri.org/")
        CustTagEnqBaseDTO custTagEnqBaseDTO);

    /**
     * 
     * @param custNum
     * @param systemId
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.ArrayOfDataPrivacyLtsDTO
     */
    @WebMethod(action = "http://www.openuri.org/getCustDataPrivacyEnquiry")
    @WebResult(name = "getCustDataPrivacyEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCustDataPrivacyEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCustDataPrivacyEnquiry")
    @ResponseWrapper(localName = "getCustDataPrivacyEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetCustDataPrivacyEnquiryResponse")
    public ArrayOfDataPrivacyLtsDTO getCustDataPrivacyEnquiry(
        @WebParam(name = "custNum", targetNamespace = "http://www.openuri.org/")
        String custNum,
        @WebParam(name = "systemId", targetNamespace = "http://www.openuri.org/")
        String systemId);

    /**
     * 
     * @param dataPrivacyObj
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.DataPrivacyLtsDTO
     */
    @WebMethod(action = "http://www.openuri.org/updateCustDataPrivacy")
    @WebResult(name = "updateCustDataPrivacyResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "updateCustDataPrivacy", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.UpdateCustDataPrivacy")
    @ResponseWrapper(localName = "updateCustDataPrivacyResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.UpdateCustDataPrivacyResponse")
    public DataPrivacyLtsDTO updateCustDataPrivacy(
        @WebParam(name = "dataPrivacyObj", targetNamespace = "http://www.openuri.org/")
        ArrayOfDataPrivacyLtsDTO dataPrivacyObj);

    /**
     * 
     * @param customerProfileDTO
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.CustomerProfileResponse
     */
    @WebMethod(action = "http://www.openuri.org/createCustomerProfile")
    @WebResult(name = "createCustomerProfileResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "createCustomerProfile", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.CreateCustomerProfile")
    @ResponseWrapper(localName = "createCustomerProfileResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.CreateCustomerProfileResponse")
    public CustomerProfileResponse createCustomerProfile(
        @WebParam(name = "customerProfileDTO", targetNamespace = "http://www.openuri.org/")
        CustomerProfileDTO customerProfileDTO);

    /**
     * 
     * @param acctNum
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.CallPlanInfoEnqResponse
     */
    @WebMethod(action = "http://www.openuri.org/getIddCallPlanEnquiry")
    @WebResult(name = "getIddCallPlanEnquiryResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getIddCallPlanEnquiry", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetIddCallPlanEnquiry")
    @ResponseWrapper(localName = "getIddCallPlanEnquiryResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.GetIddCallPlanEnquiryResponse")
    public CallPlanInfoEnqResponse getIddCallPlanEnquiry(
        @WebParam(name = "acctNum", targetNamespace = "http://www.openuri.org/")
        String acctNum);

    /**
     * 
     * @param sbOrderId
     * @param lastUpdBy
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.custProfile.InvPreassgnJunctionMsgUpdResponse
     */
    @WebMethod(action = "http://www.openuri.org/updateInvPreassgnJunctionMsg")
    @WebResult(name = "updateInvPreassgnJunctionMsgResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "updateInvPreassgnJunctionMsg", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.UpdateInvPreassgnJunctionMsg")
    @ResponseWrapper(localName = "updateInvPreassgnJunctionMsgResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.custProfile.UpdateInvPreassgnJunctionMsgResponse")
    public InvPreassgnJunctionMsgUpdResponse updateInvPreassgnJunctionMsg(
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum,
        @WebParam(name = "sbOrderId", targetNamespace = "http://www.openuri.org/")
        String sbOrderId,
        @WebParam(name = "lastUpdBy", targetNamespace = "http://www.openuri.org/")
        String lastUpdBy);

}
