
package com.pccw.custProfileGateway.acctInfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AcctInfoSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AcctInfoSoap {


    /**
     * 
     * @param accountInfoDTO
     * @return
     *     returns com.pccw.custProfileGateway.acctInfo.AccountInfoResponse
     */
    @WebMethod(action = "http://www.openuri.org/createAccountInfo")
    @WebResult(name = "createAccountInfoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "createAccountInfo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.acctInfo.CreateAccountInfo")
    @ResponseWrapper(localName = "createAccountInfoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.acctInfo.CreateAccountInfoResponse")
    public AccountInfoResponse createAccountInfo(
        @WebParam(name = "accountInfoDTO", targetNamespace = "http://www.openuri.org/")
        AccountInfoDTO accountInfoDTO);

}
