
package com.pccw.cancelOrder;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CancelOrder", targetNamespace = "http://www.openuri.org/", wsdlLocation = "file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/CancelOrder.wsdl")
public class CancelOrder
    extends Service
{

    private final static URL CANCELORDER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pccw.cancelOrder.CancelOrder.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pccw.cancelOrder.CancelOrder.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/CancelOrder.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/CancelOrder.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CANCELORDER_WSDL_LOCATION = url;
    }

    public CancelOrder(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancelOrder() {
        super(CANCELORDER_WSDL_LOCATION, new QName("http://www.openuri.org/", "CancelOrder"));
    }

    /**
     * 
     * @return
     *     returns CancelOrderSoap
     */
    @WebEndpoint(name = "CancelOrderSoap")
    public CancelOrderSoap getCancelOrderSoap() {
        return super.getPort(new QName("http://www.openuri.org/", "CancelOrderSoap"), CancelOrderSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelOrderSoap
     */
    @WebEndpoint(name = "CancelOrderSoap")
    public CancelOrderSoap getCancelOrderSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.openuri.org/", "CancelOrderSoap"), CancelOrderSoap.class, features);
    }

}
