
package com.pccw.appendOrdRmk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AppendOrdRmkSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AppendOrdRmkSoap {


    /**
     * 
     * @param pOrderRemarkDTO
     * @return
     *     returns com.pccw.appendOrdRmk.ServiceResponseDTO
     */
    @WebMethod(action = "http://www.openuri.org/appendOrdRmk")
    @WebResult(name = "appendOrdRmkResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "appendOrdRmk", targetNamespace = "http://www.openuri.org/", className = "com.pccw.appendOrdRmk.AppendOrdRmk")
    @ResponseWrapper(localName = "appendOrdRmkResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.appendOrdRmk.AppendOrdRmkResponse")
    public ServiceResponseDTO appendOrdRmk(
        @WebParam(name = "pOrderRemarkDTO", targetNamespace = "http://www.openuri.org/")
        OrderRemarkDTO pOrderRemarkDTO);

}
