
package com.pccw.dwfmGateway.orderInformation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderInformationSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderInformationSoap {


    /**
     * 
     */
    @WebMethod(action = "http://www.openuri.org/create")
    @RequestWrapper(localName = "create", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.CreateResponse")
    public void create();

    /**
     * 
     * @param pOrderInfo
     * @return
     *     returns com.pccw.dwfmGateway.orderInformation.OrderInformationResponse
     */
    @WebMethod(action = "http://www.openuri.org/getOrderInformation")
    @WebResult(name = "getOrderInformationResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getOrderInformation", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.GetOrderInformation")
    @ResponseWrapper(localName = "getOrderInformationResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.GetOrderInformationResponse")
    public OrderInformationResponse getOrderInformation(
        @WebParam(name = "pOrderInfo", targetNamespace = "http://www.openuri.org/")
        OrderInformationInput pOrderInfo);

    /**
     * 
     * @param pDetermineWkgReq
     * @return
     *     returns com.pccw.dwfmGateway.orderInformation.OrderInformationResponse
     */
    @WebMethod(action = "http://www.openuri.org/determineWorkGroup")
    @WebResult(name = "determineWorkGroupResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "determineWorkGroup", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.DetermineWorkGroup")
    @ResponseWrapper(localName = "determineWorkGroupResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.DetermineWorkGroupResponse")
    public OrderInformationResponse determineWorkGroup(
        @WebParam(name = "pDetermineWkgReq", targetNamespace = "http://www.openuri.org/")
        ArrayOfDetermineWkgReq pDetermineWkgReq);

    /**
     * 
     * @param pOrderDetailsIn
     * @return
     *     returns com.pccw.dwfmGateway.orderInformation.OrderInformationResponse
     */
    @WebMethod(action = "http://www.openuri.org/getOrderDetails")
    @WebResult(name = "getOrderDetailsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getOrderDetails", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.GetOrderDetails")
    @ResponseWrapper(localName = "getOrderDetailsResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.dwfmGateway.orderInformation.GetOrderDetailsResponse")
    public OrderInformationResponse getOrderDetails(
        @WebParam(name = "pOrderDetailsIn", targetNamespace = "http://www.openuri.org/")
        ArrayOfOrderDetailsIn pOrderDetailsIn);

}
