
package com.pccw.dwfmGateway.orderInformation;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderInformation", targetNamespace = "http://www.openuri.org/", wsdlLocation = "file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/OrderInformation.wsdl")
public class OrderInformation
    extends Service
{

    private final static URL ORDERINFORMATION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pccw.dwfmGateway.orderInformation.OrderInformation.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pccw.dwfmGateway.orderInformation.OrderInformation.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/OrderInformation.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/OrderInformation.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERINFORMATION_WSDL_LOCATION = url;
    }

    public OrderInformation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderInformation() {
        super(ORDERINFORMATION_WSDL_LOCATION, new QName("http://www.openuri.org/", "OrderInformation"));
    }

    /**
     * 
     * @return
     *     returns OrderInformationSoap
     */
    @WebEndpoint(name = "OrderInformationSoap")
    public OrderInformationSoap getOrderInformationSoap() {
        return super.getPort(new QName("http://www.openuri.org/", "OrderInformationSoap"), OrderInformationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderInformationSoap
     */
    @WebEndpoint(name = "OrderInformationSoap")
    public OrderInformationSoap getOrderInformationSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.openuri.org/", "OrderInformationSoap"), OrderInformationSoap.class, features);
    }

}
