
package com.pccw.custProfileGateway.serviceProf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceProfSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceProfSoap {


    /**
     * 
     * @param srvType
     * @param systemId
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.serviceProf.SrvAddEnqResponse
     */
    @WebMethod(action = "http://www.openuri.org/getServiceAddr")
    @WebResult(name = "getServiceAddrResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getServiceAddr", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetServiceAddr")
    @ResponseWrapper(localName = "getServiceAddrResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetServiceAddrResponse")
    public SrvAddEnqResponse getServiceAddr(
        @WebParam(name = "srvType", targetNamespace = "http://www.openuri.org/")
        String srvType,
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum,
        @WebParam(name = "systemId", targetNamespace = "http://www.openuri.org/")
        String systemId);

    /**
     * 
     * @param srvType
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.serviceProf.ArrayOfArpuInfoDTO
     */
    @WebMethod(action = "http://www.openuri.org/getIddffpInfo")
    @WebResult(name = "getIddffpInfoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getIddffpInfo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetIddffpInfo")
    @ResponseWrapper(localName = "getIddffpInfoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetIddffpInfoResponse")
    public ArrayOfArpuInfoDTO getIddffpInfo(
        @WebParam(name = "srvType", targetNamespace = "http://www.openuri.org/")
        String srvType,
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum);

    /**
     * 
     * @param boc
     * @param srvType
     * @param projectCd
     * @param specialSrvGrp
     * @param specialSrvName
     * @param datCd
     * @param accountCd
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.serviceProf.ArrayOfDNAssignmentResultDTO
     */
    @WebMethod(action = "http://www.openuri.org/getDNAssignmentResult")
    @WebResult(name = "getDNAssignmentResultResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDNAssignmentResult", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetDNAssignmentResult")
    @ResponseWrapper(localName = "getDNAssignmentResultResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetDNAssignmentResultResponse")
    public ArrayOfDNAssignmentResultDTO getDNAssignmentResult(
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum,
        @WebParam(name = "accountCd", targetNamespace = "http://www.openuri.org/")
        String accountCd,
        @WebParam(name = "boc", targetNamespace = "http://www.openuri.org/")
        String boc,
        @WebParam(name = "projectCd", targetNamespace = "http://www.openuri.org/")
        String projectCd,
        @WebParam(name = "srvType", targetNamespace = "http://www.openuri.org/")
        String srvType,
        @WebParam(name = "datCd", targetNamespace = "http://www.openuri.org/")
        String datCd,
        @WebParam(name = "specialSrvGrp", targetNamespace = "http://www.openuri.org/")
        String specialSrvGrp,
        @WebParam(name = "specialSrvName", targetNamespace = "http://www.openuri.org/")
        String specialSrvName);

    /**
     * 
     * @param gatewayNum
     * @param srvType
     * @param inventStsCd
     * @param action
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.serviceProf.DNAssignOutput
     */
    @WebMethod(action = "http://www.openuri.org/dnAssignReq")
    @WebResult(name = "dnAssignReqResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "dnAssignReq", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.DnAssignReq")
    @ResponseWrapper(localName = "dnAssignReqResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.DnAssignReqResponse")
    public DNAssignOutput dnAssignReq(
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum,
        @WebParam(name = "inventStsCd", targetNamespace = "http://www.openuri.org/")
        String inventStsCd,
        @WebParam(name = "action", targetNamespace = "http://www.openuri.org/")
        String action,
        @WebParam(name = "srvType", targetNamespace = "http://www.openuri.org/")
        String srvType,
        @WebParam(name = "gatewayNum", targetNamespace = "http://www.openuri.org/")
        String gatewayNum);

    /**
     * 
     * @param srvType
     * @param inventStsCd
     * @param action
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.serviceProf.ServiceResponse
     */
    @WebMethod(operationName = "DNStatusAssig", action = "http://www.openuri.org/DNStatusAssig")
    @WebResult(name = "DNStatusAssigResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "DNStatusAssig", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.DNStatusAssig")
    @ResponseWrapper(localName = "DNStatusAssigResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.DNStatusAssigResponse")
    public ServiceResponse dnStatusAssig(
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum,
        @WebParam(name = "inventStsCd", targetNamespace = "http://www.openuri.org/")
        String inventStsCd,
        @WebParam(name = "action", targetNamespace = "http://www.openuri.org/")
        String action,
        @WebParam(name = "srvType", targetNamespace = "http://www.openuri.org/")
        String srvType);

    /**
     * 
     * @param srvType
     * @param srvNum
     * @return
     *     returns com.pccw.custProfileGateway.serviceProf.ExtgInvInfoReturn
     */
    @WebMethod(action = "http://www.openuri.org/getDrgSvcDetail")
    @WebResult(name = "getDrgSvcDetailResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDrgSvcDetail", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetDrgSvcDetail")
    @ResponseWrapper(localName = "getDrgSvcDetailResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetDrgSvcDetailResponse")
    public ExtgInvInfoReturn getDrgSvcDetail(
        @WebParam(name = "srvNum", targetNamespace = "http://www.openuri.org/")
        String srvNum,
        @WebParam(name = "srvType", targetNamespace = "http://www.openuri.org/")
        String srvType);

    /**
     * 
     * @param serviceId
     * @param acctNum
     * @param systemId
     * @param effectiveInd
     * @return
     *     returns com.pccw.custProfileGateway.serviceProf.ArrayOfOfferDetailRecurringChargesDTO
     */
    @WebMethod(action = "http://www.openuri.org/getRecurringCharges")
    @WebResult(name = "getRecurringChargesResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getRecurringCharges", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetRecurringCharges")
    @ResponseWrapper(localName = "getRecurringChargesResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.custProfileGateway.serviceProf.GetRecurringChargesResponse")
    public ArrayOfOfferDetailRecurringChargesDTO getRecurringCharges(
        @WebParam(name = "systemId", targetNamespace = "http://www.openuri.org/")
        String systemId,
        @WebParam(name = "acctNum", targetNamespace = "http://www.openuri.org/")
        String acctNum,
        @WebParam(name = "serviceId", targetNamespace = "http://www.openuri.org/")
        String serviceId,
        @WebParam(name = "effectiveInd", targetNamespace = "http://www.openuri.org/")
        String effectiveInd);

}
