
package com.pccw.updateSRD;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UpdateSRD", targetNamespace = "http://www.openuri.org/", wsdlLocation = "file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/UpdateSRD.wsdl")
public class UpdateSRD_Service
    extends Service
{

    private final static URL UPDATESRD_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pccw.updateSRD.UpdateSRD_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pccw.updateSRD.UpdateSRD_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/UpdateSRD.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/pvcs/working/BOM/Programs/Springboard/SBWPR3/SpringboardWsClient/wsdl/UpdateSRD.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        UPDATESRD_WSDL_LOCATION = url;
    }

    public UpdateSRD_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateSRD_Service() {
        super(UPDATESRD_WSDL_LOCATION, new QName("http://www.openuri.org/", "UpdateSRD"));
    }

    /**
     * 
     * @return
     *     returns UpdateSRDSoap
     */
    @WebEndpoint(name = "UpdateSRDSoap")
    public UpdateSRDSoap getUpdateSRDSoap() {
        return super.getPort(new QName("http://www.openuri.org/", "UpdateSRDSoap"), UpdateSRDSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateSRDSoap
     */
    @WebEndpoint(name = "UpdateSRDSoap")
    public UpdateSRDSoap getUpdateSRDSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.openuri.org/", "UpdateSRDSoap"), UpdateSRDSoap.class, features);
    }

}
