
package com.pccw.updateSRD;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UpdateSRDSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateSRDSoap {


    /**
     * 
     */
    @WebMethod(action = "http://www.openuri.org/create")
    @RequestWrapper(localName = "create", targetNamespace = "http://www.openuri.org/", className = "com.pccw.updateSRD.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.updateSRD.CreateResponse")
    public void create();

    /**
     * 
     * @param pWithAppointment
     * @param pSrdDTO
     * @return
     *     returns com.pccw.updateSRD.ServiceResponseDTO
     */
    @WebMethod(operationName = "UpdateSRD", action = "http://www.openuri.org/UpdateSRD")
    @WebResult(name = "UpdateSRDResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "UpdateSRD", targetNamespace = "http://www.openuri.org/", className = "com.pccw.updateSRD.UpdateSRD")
    @ResponseWrapper(localName = "UpdateSRDResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.updateSRD.UpdateSRDResponse")
    public ServiceResponseDTO updateSRD(
        @WebParam(name = "pSrdDTO", targetNamespace = "http://www.openuri.org/")
        SrdDTO pSrdDTO,
        @WebParam(name = "pWithAppointment", targetNamespace = "http://www.openuri.org/")
        String pWithAppointment);

}
