
package com.pccw.pposGateway.edgePos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PPOSSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PPOSSoap {


    /**
     * 
     * @param pStoreIP
     * @param pOrderRegInfo
     * @return
     *     returns com.pccw.pposGateway.edgePos.SalesMemoResponse
     */
    @WebMethod(action = "http://www.openuri.org/createSalesMemo")
    @WebResult(name = "createSalesMemoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "createSalesMemo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.pposGateway.edgePos.CreateSalesMemo")
    @ResponseWrapper(localName = "createSalesMemoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.pposGateway.edgePos.CreateSalesMemoResponse")
    public SalesMemoResponse createSalesMemo(
        @WebParam(name = "pStoreIP", targetNamespace = "http://www.openuri.org/")
        String pStoreIP,
        @WebParam(name = "pOrderRegInfo", targetNamespace = "http://www.openuri.org/")
        String pOrderRegInfo);

    /**
     * 
     * @param pStoreIP
     * @param pSalesMemoNum
     * @return
     *     returns com.pccw.pposGateway.edgePos.RetrieveSalesMemoReturn
     */
    @WebMethod(action = "http://www.openuri.org/retrieveSalesMemo")
    @WebResult(name = "retrieveSalesMemoResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "retrieveSalesMemo", targetNamespace = "http://www.openuri.org/", className = "com.pccw.pposGateway.edgePos.RetrieveSalesMemo")
    @ResponseWrapper(localName = "retrieveSalesMemoResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.pposGateway.edgePos.RetrieveSalesMemoResponse")
    public RetrieveSalesMemoReturn retrieveSalesMemo(
        @WebParam(name = "pStoreIP", targetNamespace = "http://www.openuri.org/")
        String pStoreIP,
        @WebParam(name = "pSalesMemoNum", targetNamespace = "http://www.openuri.org/")
        String pSalesMemoNum);

    /**
     * 
     * @param pStoreIP
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getPposBusinessDate")
    @WebResult(name = "getPposBusinessDateResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getPposBusinessDate", targetNamespace = "http://www.openuri.org/", className = "com.pccw.pposGateway.edgePos.GetPposBusinessDate")
    @ResponseWrapper(localName = "getPposBusinessDateResponse", targetNamespace = "http://www.openuri.org/", className = "com.pccw.pposGateway.edgePos.GetPposBusinessDateResponse")
    public String getPposBusinessDate(
        @WebParam(name = "pStoreIP", targetNamespace = "http://www.openuri.org/")
        String pStoreIP);

}
