//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 10:56:32 AM CST 
//


package com.bomwebportal.lts.wsServiceLts.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OfferDetailsProfile" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="conditionEffEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="conditionEffStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="expiredMonths" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="promotionEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="promotionExpiredMonths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="promotionStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="iddCallPlanCds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offerDetailsProfile",
    "iddCallPlanCds"
})
@XmlRootElement(name = "ItemDetailsProfileRequest")
public class ItemDetailsProfileRequest {

    @XmlElement(name = "OfferDetailsProfile", required = true)
    protected List<ItemDetailsProfileRequest.OfferDetailsProfile> offerDetailsProfile;
    @XmlElement(required = true, nillable = true)
    protected List<String> iddCallPlanCds;

    /**
     * Gets the value of the offerDetailsProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerDetailsProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferDetailsProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemDetailsProfileRequest.OfferDetailsProfile }
     * 
     * 
     */
    public List<ItemDetailsProfileRequest.OfferDetailsProfile> getOfferDetailsProfile() {
        if (offerDetailsProfile == null) {
            offerDetailsProfile = new ArrayList<ItemDetailsProfileRequest.OfferDetailsProfile>();
        }
        return this.offerDetailsProfile;
    }

    /**
     * Gets the value of the iddCallPlanCds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iddCallPlanCds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIddCallPlanCds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIddCallPlanCds() {
        if (iddCallPlanCds == null) {
            iddCallPlanCds = new ArrayList<String>();
        }
        return this.iddCallPlanCds;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="conditionEffEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="conditionEffStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="expiredMonths" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="promotionEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="promotionExpiredMonths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="promotionStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "conditionEffEndDate",
        "conditionEffStartDate",
        "expiredMonths",
        "offerId",
        "promotionEndDate",
        "promotionExpiredMonths",
        "promotionStartDate"
    })
    public static class OfferDetailsProfile {

        protected String conditionEffEndDate;
        protected String conditionEffStartDate;
        protected double expiredMonths;
        protected String offerId;
        protected String promotionEndDate;
        protected String promotionExpiredMonths;
        protected String promotionStartDate;

        /**
         * Gets the value of the conditionEffEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConditionEffEndDate() {
            return conditionEffEndDate;
        }

        /**
         * Sets the value of the conditionEffEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConditionEffEndDate(String value) {
            this.conditionEffEndDate = value;
        }

        /**
         * Gets the value of the conditionEffStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConditionEffStartDate() {
            return conditionEffStartDate;
        }

        /**
         * Sets the value of the conditionEffStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConditionEffStartDate(String value) {
            this.conditionEffStartDate = value;
        }

        /**
         * Gets the value of the expiredMonths property.
         * 
         */
        public double getExpiredMonths() {
            return expiredMonths;
        }

        /**
         * Sets the value of the expiredMonths property.
         * 
         */
        public void setExpiredMonths(double value) {
            this.expiredMonths = value;
        }

        /**
         * Gets the value of the offerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOfferId() {
            return offerId;
        }

        /**
         * Sets the value of the offerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOfferId(String value) {
            this.offerId = value;
        }

        /**
         * Gets the value of the promotionEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPromotionEndDate() {
            return promotionEndDate;
        }

        /**
         * Sets the value of the promotionEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPromotionEndDate(String value) {
            this.promotionEndDate = value;
        }

        /**
         * Gets the value of the promotionExpiredMonths property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPromotionExpiredMonths() {
            return promotionExpiredMonths;
        }

        /**
         * Sets the value of the promotionExpiredMonths property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPromotionExpiredMonths(String value) {
            this.promotionExpiredMonths = value;
        }

        /**
         * Gets the value of the promotionStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPromotionStartDate() {
            return promotionStartDate;
        }

        /**
         * Sets the value of the promotionStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPromotionStartDate(String value) {
            this.promotionStartDate = value;
        }

    }

}
